# Generated by Django 5.2.16 on 2026-07-31 13:44

import core.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectionRegionale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Ex. : DRAN, DRAS, DRCE. Sert de préfixe aux tickets et de dossier de stockage.",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code direction doit contenir de 2 à 10 caractères majuscules ou chiffres.",
                                regex="^[A-Z0-9]{2,10}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("actif", models.BooleanField(default=True)),
                (
                    "cree_le",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "direction régionale",
                "verbose_name_plural": "directions régionales",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9._-]{2,30}$", "Matricule invalide."
                            )
                        ],
                        verbose_name="matricule",
                    ),
                ),
                ("nom", models.CharField(max_length=80)),
                ("prenoms", models.CharField(max_length=160)),
                ("fonction", models.CharField(blank=True, default="", max_length=120)),
                ("site", models.CharField(blank=True, default="", max_length=120)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True, verbose_name="doit changer son mot de passe"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="accès à l'administration"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un compte technique national (superutilisateur).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents",
                        to="core.directionregionale",
                        verbose_name="direction régionale",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent",
                "verbose_name_plural": "agents",
                "ordering": ["nom", "prenoms"],
            },
            managers=[
                ("objects", core.managers.AgentManager()),
            ],
        ),
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                (
                    "code_secteur",
                    models.CharField(
                        db_index=True,
                        default="000",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code secteur doit contenir de 1 à 3 caractères alphanumériques.",
                                regex="^[A-Za-z0-9]{1,3}$",
                            )
                        ],
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)ss",
                        to="core.directionregionale",
                        verbose_name="direction régionale",
                    ),
                ),
            ],
            options={
                "verbose_name": "agence",
                "verbose_name_plural": "agences",
                "ordering": ["direction", "code_secteur", "nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("direction", "nom"),
                        name="uniq_agence_nom_par_direction",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                (
                    "code_secteur",
                    models.CharField(
                        db_index=True,
                        default="000",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code secteur doit contenir de 1 à 3 caractères alphanumériques.",
                                regex="^[A-Za-z0-9]{1,3}$",
                            )
                        ],
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)ss",
                        to="core.directionregionale",
                        verbose_name="direction régionale",
                    ),
                ),
            ],
            options={
                "verbose_name": "secteur",
                "verbose_name_plural": "secteurs",
                "ordering": ["direction", "nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("direction", "nom"),
                        name="uniq_secteur_nom_par_direction",
                    ),
                    models.UniqueConstraint(
                        fields=("direction", "code_secteur"),
                        name="uniq_secteur_code_par_direction",
                    ),
                ],
            },
        ),
    ]
