# Generated by Django 5.2.16 on 2026-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_direction_et_profils_par_defaut"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMetier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("nom", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "url_base",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Adresse publique de l'application, ex. https://visite.dran.ci/",
                        max_length=200,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "application métier",
                "verbose_name_plural": "applications métier",
                "ordering": ["code"],
                "permissions": [
                    ("acces_recouvrement", "Rétablissement : accéder à l'application"),
                    (
                        "importer_donnees",
                        "Rétablissement : importer impayés et paiements",
                    ),
                    ("exporter_donnees", "Rétablissement : télécharger les exports"),
                    (
                        "valider_reclamation",
                        "Rétablissement : valider une réclamation client",
                    ),
                    (
                        "gerer_sauvegardes",
                        "Rétablissement : consulter et supprimer les sauvegardes",
                    ),
                    (
                        "acces_visite_client",
                        "Visite client : accéder au portail agence",
                    ),
                    (
                        "saisir_passage",
                        "Visite client : enregistrer les passages accueil et caisse",
                    ),
                    (
                        "corriger_passage",
                        "Visite client : corriger le motif d'un passage",
                    ),
                    (
                        "saisir_bilan_caisse",
                        "Visite client : saisir le bilan de caisse",
                    ),
                    (
                        "acces_tableau_bord",
                        "Visite client : consulter les tableaux de bord",
                    ),
                    ("valider_plainte", "Visite client : valider les plaintes clients"),
                ],
            },
        ),
    ]
