# Generated by Django 5.2.16 on 2026-08-13 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_nettoyage_permissions_heritees"),
    ]

    operations = [
        migrations.AddField(
            model_name="directionregionale",
            name="code_secteur",
            field=models.CharField(
                default="000",
                help_text="Identifiant numérique de la direction elle-même, dans le même espace que ses secteurs (ex. DRAN=040, secteurs 041 à 049).",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le code secteur doit contenir de 1 à 3 caractères alphanumériques.",
                        regex="^[A-Za-z0-9]{1,3}$",
                    )
                ],
                verbose_name="code (espace secteurs)",
            ),
        ),
    ]
