# Generated by Django 5.2.16 on 2026-08-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_applicationmetier_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationmetier",
            options={
                "ordering": ["code"],
                "permissions": [
                    ("acces_recouvrement", "Rétablissement : accéder à l'application"),
                    (
                        "importer_donnees",
                        "Rétablissement : importer impayés et paiements",
                    ),
                    ("exporter_donnees", "Rétablissement : télécharger les exports"),
                    (
                        "valider_reclamation",
                        "Rétablissement : valider une réclamation client",
                    ),
                    (
                        "gerer_sauvegardes",
                        "Rétablissement : consulter et supprimer les sauvegardes",
                    ),
                    (
                        "acces_visite_client",
                        "Visite client : accéder au portail agence",
                    ),
                    (
                        "saisir_passage",
                        "Visite client : enregistrer les passages accueil et caisse",
                    ),
                    (
                        "corriger_passage",
                        "Visite client : corriger le motif d'un passage",
                    ),
                    (
                        "saisir_bilan_caisse",
                        "Visite client : saisir le bilan de caisse",
                    ),
                    (
                        "acces_tableau_bord",
                        "Visite client : consulter les tableaux de bord",
                    ),
                    ("valider_plainte", "Visite client : valider les plaintes clients"),
                    (
                        "gerer_utilisateurs",
                        "Socle : gérer les utilisateurs et leurs droits",
                    ),
                    ("acces_coupure", "Coupure : accéder à l'application"),
                ],
                "verbose_name": "application métier",
                "verbose_name_plural": "applications métier",
            },
        ),
    ]
