# Generated by Django 5.2.16 on 2026-08-20 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_applicationmetier_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationmetier",
            options={
                "ordering": ["code"],
                "permissions": [
                    (
                        "gerer_utilisateurs",
                        "Socle : gérer les utilisateurs et leurs droits",
                    )
                ],
                "verbose_name": "application métier",
                "verbose_name_plural": "applications métier",
            },
        ),
        migrations.CreateModel(
            name="AccesApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profil", models.CharField(max_length=100)),
                ("actif", models.BooleanField(default=True)),
                ("accorde_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "accorde_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acces_accordes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acces_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acces",
                        to="core.applicationmetier",
                    ),
                ),
            ],
            options={
                "verbose_name": "accès application",
                "verbose_name_plural": "accès applications",
                "ordering": ["application", "agent"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent", "application"),
                        name="uniq_acces_par_application",
                    )
                ],
            },
        ),
    ]
