# Generated by Django 5.2.17 on 2026-09-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_renomme_profils_par_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="mot_de_passe_defini_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="mot de passe attribué le"
            ),
        ),
    ]
