# Generated by Django 5.1.4 on 2026-09-10 11:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                ("libelle", models.CharField(max_length=150, verbose_name="libellé")),
                (
                    "type_structure",
                    models.CharField(
                        choices=[
                            ("DR", "Direction Régionale"),
                            ("DC", "Direction Centrale"),
                        ],
                        default="DR",
                        max_length=2,
                        verbose_name="type",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "code_direction_dran",
                    models.CharField(
                        blank=True,
                        help_text="Code de la DirectionRegionale correspondante côté django_dran, si applicable.",
                        max_length=20,
                        verbose_name="code direction régionale (socle DRAN)",
                    ),
                ),
            ],
            options={
                "verbose_name": "structure",
                "verbose_name_plural": "structures",
                "ordering": ["-type_structure", "code"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueDelai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("champ", models.CharField(max_length=60, verbose_name="champ")),
                (
                    "ancienne_valeur",
                    models.CharField(max_length=40, verbose_name="ancienne valeur"),
                ),
                (
                    "nouvelle_valeur",
                    models.CharField(max_length=40, verbose_name="nouvelle valeur"),
                ),
                ("modifie_le", models.DateTimeField(auto_now_add=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historique de délai",
                "verbose_name_plural": "historique des délais",
                "ordering": ["-modifie_le"],
            },
        ),
        migrations.CreateModel(
            name="ParametreDelai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delai_compteur_shunte",
                    models.PositiveIntegerField(
                        default=48,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="délai compteur shunté (heures)",
                    ),
                ),
                (
                    "delai_sans_electricite",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="délai client sans électricité (heures)",
                    ),
                ),
                (
                    "delai_autre_equipement",
                    models.PositiveIntegerField(
                        default=48,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="délai autres équipements (heures)",
                    ),
                ),
                (
                    "seuil_alerte_pct",
                    models.PositiveIntegerField(
                        default=75,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="seuil d'alerte anticipée (%)",
                    ),
                ),
                (
                    "appliquer_dossiers_ouverts",
                    models.BooleanField(
                        default=False,
                        verbose_name="appliquer aux dossiers déjà ouverts",
                    ),
                ),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parametres_delai_modifies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètre de délai",
                "verbose_name_plural": "paramètres de délai",
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="code"),
                ),
                ("libelle", models.CharField(max_length=150, verbose_name="libellé")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secteurs",
                        to="referentiel.structure",
                        verbose_name="structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "secteur",
                "verbose_name_plural": "secteurs",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="AffectationAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectation_depannage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="agent",
                    ),
                ),
                (
                    "secteurs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laisser vide pour donner accès à tous les secteurs de la structure.",
                        related_name="agents_affectes",
                        to="referentiel.secteur",
                        verbose_name="secteurs visibles",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents_affectes",
                        to="referentiel.structure",
                        verbose_name="structure de rattachement",
                    ),
                ),
            ],
            options={
                "verbose_name": "affectation d'agent",
                "verbose_name_plural": "affectations d'agents",
            },
        ),
        migrations.CreateModel(
            name="Quartier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("COMMUNE", "Commune"),
                            ("QUARTIER", "Quartier"),
                            ("SOUS_QUARTIER", "Sous-quartier"),
                        ],
                        default="QUARTIER",
                        max_length=13,
                        verbose_name="niveau",
                    ),
                ),
                (
                    "osm_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="identifiant OSM",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="source du découpage"
                    ),
                ),
                ("contour", models.JSONField(verbose_name="contour GeoJSON")),
                ("lat_min", models.FloatField(db_index=True)),
                ("lat_max", models.FloatField(db_index=True)),
                ("lon_min", models.FloatField(db_index=True)),
                ("lon_max", models.FloatField(db_index=True)),
                ("centre_lat", models.FloatField()),
                ("centre_lon", models.FloatField()),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                ("importe_le", models.DateTimeField(auto_now_add=True)),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"niveau": "COMMUNE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quartiers",
                        to="referentiel.quartier",
                        verbose_name="commune de rattachement",
                    ),
                ),
                (
                    "quartier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"niveau": "QUARTIER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_quartiers",
                        to="referentiel.quartier",
                        verbose_name="quartier de rattachement",
                    ),
                ),
            ],
            options={
                "verbose_name": "quartier",
                "verbose_name_plural": "quartiers et communes",
                "ordering": ["niveau", "nom"],
                "indexes": [
                    models.Index(
                        fields=["niveau", "actif"], name="referentiel_niveau_a1938c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=150, verbose_name="libellé")),
                (
                    "code",
                    models.CharField(blank=True, max_length=40, verbose_name="code"),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="catégorie"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipements",
                        to="referentiel.structure",
                        verbose_name="structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "équipement",
                "verbose_name_plural": "équipements",
                "ordering": [
                    "-structure__type_structure",
                    "structure__code",
                    "libelle",
                ],
                "unique_together": {("structure", "libelle")},
            },
        ),
    ]
