# Generated by Django 5.1.4 on 2026-09-10 11:45

import depannages.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Depannage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_bt",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="N BT / BTA"
                    ),
                ),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("DEFINITIF", "Définitif"),
                            ("PROVISOIRE", "Provisoire"),
                        ],
                        max_length=12,
                        verbose_name="type d'intervention",
                    ),
                ),
                (
                    "categorie_provisoire",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPTEUR_SHUNTE", "Compteur shunté"),
                            ("SANS_ELECTRICITE", "Client sans électricité"),
                            ("AUTRE_EQUIPEMENT", "Autre équipement"),
                        ],
                        max_length=20,
                        verbose_name="catégorie du provisoire",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                (
                    "precision_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="précision GPS (m)"
                    ),
                ),
                (
                    "adresse_saisie",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="repérage / adresse"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SAISI", "Saisi"),
                            ("EN_COURS", "En cours"),
                            ("REGULARISE", "Clôturé"),
                            ("CLOTURE", "Clôturé (définitif)"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        db_index=True,
                        default="SAISI",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "delai_applique_heures",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="délai appliqué (heures)"
                    ),
                ),
                (
                    "date_saisie",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date de saisie",
                    ),
                ),
                (
                    "date_regularisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de clôture définitive"
                    ),
                ),
                (
                    "synchronise",
                    models.BooleanField(default=True, verbose_name="synchronisé"),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depannages_commune",
                        to="referentiel.quartier",
                        verbose_name="commune",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depannages_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsable d'ouverture",
                    ),
                ),
                (
                    "equipements",
                    models.ManyToManyField(
                        related_name="depannages",
                        to="referentiel.equipement",
                        verbose_name="équipements concernés",
                    ),
                ),
                (
                    "quartier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depannages",
                        to="referentiel.quartier",
                        verbose_name="quartier",
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depannages",
                        to="referentiel.secteur",
                        verbose_name="secteur",
                    ),
                ),
                (
                    "sous_quartier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depannages_sous_quartier",
                        to="referentiel.quartier",
                        verbose_name="sous-quartier",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depannages",
                        to="referentiel.structure",
                        verbose_name="structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "dépannage",
                "verbose_name_plural": "dépannages",
                "ordering": ["-date_saisie"],
            },
        ),
        migrations.CreateModel(
            name="ClotureStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_cloture",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de clôture"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire de clôture"),
                ),
                (
                    "cloture_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clotures_realisees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsable de clôture",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clotures",
                        to="referentiel.structure",
                    ),
                ),
                (
                    "depannage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clotures",
                        to="depannages.depannage",
                    ),
                ),
            ],
            options={
                "verbose_name": "clôture par structure",
                "verbose_name_plural": "clôtures par structure",
                "ordering": ["date_cloture"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueStatut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut_avant",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="statut avant"
                    ),
                ),
                (
                    "statut_apres",
                    models.CharField(max_length=12, verbose_name="statut après"),
                ),
                ("action", models.CharField(max_length=150, verbose_name="action")),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "depannage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="depannages.depannage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historique",
                "verbose_name_plural": "historique",
                "ordering": ["-horodatage"],
            },
        ),
        migrations.CreateModel(
            name="PhotoDepannage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_photo",
                    models.CharField(
                        choices=[
                            ("OUVRAGE", "Photo de l'ouvrage"),
                            ("FICHE_AVIS", "Photo de la fiche d'avis"),
                            ("BON_DEPANNAGE", "Bon de dépannage (clôture)"),
                            ("EQUIP_CLOT", "Photo équipement (clôture)"),
                        ],
                        max_length=14,
                        verbose_name="type",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("CAMERA", "Prise dans l'application"),
                            ("GALERIE", "Fichier joint"),
                        ],
                        default="CAMERA",
                        max_length=8,
                        verbose_name="origine",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=depannages.models.chemin_photo, verbose_name="image"
                    ),
                ),
                ("ajoutee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cloture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="depannages.cloturestructure",
                    ),
                ),
                (
                    "depannage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="depannages.depannage",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "verbose_name_plural": "photos",
                "ordering": ["type_photo", "ajoutee_le"],
            },
        ),
        migrations.AddIndex(
            model_name="depannage",
            index=models.Index(
                fields=["type_intervention", "statut"],
                name="depannages__type_in_ede498_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="depannage",
            index=models.Index(
                fields=["categorie_provisoire"], name="depannages__categor_3ab646_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cloturestructure",
            unique_together={("depannage", "structure")},
        ),
    ]
