# Generated by Django 5.1.4 on 2026-09-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="identifiant de clé"
                    ),
                ),
                ("public_key", models.TextField(verbose_name="clé publique")),
                (
                    "sign_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="compteur de signature"
                    ),
                ),
                (
                    "libelle_appareil",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="appareil"
                    ),
                ),
                (
                    "transports",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="transports"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="enrôlé le"),
                ),
                (
                    "derniere_utilisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière utilisation"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cles_webauthn",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "clé WebAuthn",
                "verbose_name_plural": "clés WebAuthn",
                "ordering": ["-cree_le"],
            },
        ),
    ]
